name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    permissions:
      contents: read
      security-events: write
    uses: damien-robotsix/robotsix-mill/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.12"
      install-extras: ""
      cov-package: "package_name"
      coverage-threshold: "85"
      mypy-advisory: false
