name: Release
on:
  push:
    branches: ['main']
    tags: ['v*']
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: damien-robotsix/robotsix-mill/.github/workflows/docker-release.yml@10a15c23d6c9103cd72eafe0186dbdf9714377b7  # main
    secrets: inherit
