name: Release
on:
  push:
    branches: ['main']
    tags: ['v*']
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    uses: damien-robotsix/robotsix-mill/.github/workflows/docker-release.yml@90fcbcb32974e45c86e798f6da435e430e276a99  # main
    secrets: inherit
